app:
  message: Message has been sent Successfully..
spring:
  data:
    mongodb:
      database: ${DB_NAME}
      uri: ${DB_URL}
  rabbitmq:
    addresses: ${MQ_ADDRESSES}
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey
    ssl:
      enabled: false
  security:
    user:
      password: ${USER_PASSWORD}
